/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.calculadora;

import java.awt.Color;
import java.awt.Font;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.Stack;

import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.border.Border;

/**
 *
 * @author Maria
 */
public class Calculadora extends javax.swing.JFrame {

    Color vermelho = new Color(235, 76, 76);
    Color rosaForte = new Color(255, 112, 112);
    Color rosaClaro = new Color(255, 166, 166);

    Font displayFont = new Font("Arial", Font.BOLD, 24);
    Font buttonFont = new Font("Arial", Font.BOLD, 24);

    Border displayPadding = BorderFactory.createEmptyBorder(10, 10, 10, 10);

    Border errorBorderLine = BorderFactory.createLineBorder(this.vermelho, 2);
    Border defaultBorderLine = BorderFactory.createLineBorder(this.rosaForte, 2);

    Border errorBorder = BorderFactory.createCompoundBorder(errorBorderLine, displayPadding);
    Border defaultBorder = BorderFactory.createCompoundBorder(defaultBorderLine, displayPadding);

    DecimalFormat decimalFormat = new DecimalFormat("#.##");
    List<String> operations = List.of("+", "-", "*", "/");
    Stack<String> stack = new Stack<>();

    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        numbersGroup = new javax.swing.ButtonGroup();
        operationsGroup = new javax.swing.ButtonGroup();
        functionsGroup = new javax.swing.ButtonGroup();
        display = new javax.swing.JTextField();
        number1 = new javax.swing.JButton();
        number4 = new javax.swing.JButton();
        number7 = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        number9 = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        subtractionOperation = new javax.swing.JButton();
        multiplicationOperation = new javax.swing.JButton();
        number2 = new javax.swing.JButton();
        number5 = new javax.swing.JButton();
        number8 = new javax.swing.JButton();
        number0 = new javax.swing.JButton();
        divisionOperation = new javax.swing.JButton();
        number3 = new javax.swing.JButton();
        sumOperation = new javax.swing.JButton();
        resultOperation = new javax.swing.JButton();
        number6 = new javax.swing.JButton();
        commaButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        display.setEditable(false);
        display.setBackground(rosaClaro);
        display.setFont(displayFont);
        display.setBorder(defaultBorder);
        display.setMargin(new java.awt.Insets(10, 10, 10, 10));

        number1.setBackground(rosaClaro);
        number1.setFont(buttonFont);
        number1.setText("1");
        numbersGroup.add(number1);
        number1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClickNumber(evt);
            }
        });

        number4.setBackground(rosaClaro);
        number4.setFont(buttonFont);
        number4.setText("4");
        numbersGroup.add(number4);
        number4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClickNumber(evt);
            }
        });

        number7.setBackground(rosaClaro);
        number7.setFont(buttonFont);
        number7.setText("7");
        numbersGroup.add(number7);
        number7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClickNumber(evt);
            }
        });

        clearButton.setBackground(rosaClaro);
        clearButton.setFont(buttonFont);
        clearButton.setText("CE");
        clearButton.setAutoscrolls(true);
        functionsGroup.add(clearButton);
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OnClear(evt);
            }
        });

        number9.setBackground(rosaClaro);
        number9.setFont(buttonFont);
        number9.setText("9");
        numbersGroup.add(number9);
        number9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClickNumber(evt);
            }
        });

        deleteButton.setBackground(rosaClaro);
        deleteButton.setFont(buttonFont);
        deleteButton.setText("<=");
        functionsGroup.add(deleteButton);
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onDelete(evt);
            }
        });

        subtractionOperation.setBackground(rosaClaro);
        subtractionOperation.setFont(buttonFont);
        subtractionOperation.setText("-");
        operationsGroup.add(subtractionOperation);
        subtractionOperation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClickOperation(evt);
            }
        });

        multiplicationOperation.setBackground(rosaClaro);
        multiplicationOperation.setFont(buttonFont);
        multiplicationOperation.setText("*");
        operationsGroup.add(multiplicationOperation);
        multiplicationOperation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClickOperation(evt);
            }
        });

        number2.setBackground(rosaClaro);
        number2.setFont(buttonFont);
        number2.setText("2");
        numbersGroup.add(number2);
        number2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClickNumber(evt);
            }
        });

        number5.setBackground(rosaClaro);
        number5.setFont(buttonFont);
        number5.setText("5");
        numbersGroup.add(number5);
        number5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClickNumber(evt);
            }
        });

        number8.setBackground(rosaClaro);
        number8.setFont(buttonFont);
        number8.setText("8");
        numbersGroup.add(number8);
        number8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClickNumber(evt);
            }
        });

        number0.setBackground(rosaClaro);
        number0.setFont(buttonFont);
        number0.setText("0");
        numbersGroup.add(number0);
        number0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClickNumber(evt);
            }
        });

        divisionOperation.setBackground(rosaClaro);
        divisionOperation.setFont(buttonFont);
        divisionOperation.setText("/");
        operationsGroup.add(divisionOperation);
        divisionOperation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClickOperation(evt);
            }
        });

        number3.setBackground(rosaClaro);
        number3.setFont(buttonFont);
        number3.setText("3");
        number3.setActionCommand("");
        numbersGroup.add(number3);
        number3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClickNumber(evt);
            }
        });

        sumOperation.setBackground(rosaClaro);
        sumOperation.setFont(buttonFont);
        sumOperation.setText("+");
        operationsGroup.add(sumOperation);
        sumOperation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                none(evt);
                onClickOperation(evt);
            }
        });

        resultOperation.setBackground(rosaClaro);
        resultOperation.setFont(buttonFont);
        resultOperation.setText("=");
        resultOperation.setActionCommand("");
        operationsGroup.add(resultOperation);
        resultOperation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onResult(evt);
            }
        });

        number6.setBackground(rosaClaro);
        number6.setFont(buttonFont);
        number6.setText("6");
        number6.setActionCommand("");
        numbersGroup.add(number6);
        number6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClickNumber(evt);
            }
        });

        commaButton.setBackground(rosaClaro);
        commaButton.setFont(buttonFont);
        commaButton.setText(",");
        operationsGroup.add(commaButton);
        commaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClickComma(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(display, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(number0, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(number7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                                    .addComponent(number4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(number1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(number5, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(number8, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(number2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(number3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(number6, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(number9, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(commaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sumOperation, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(multiplicationOperation, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(divisionOperation, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(subtractionOperation, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resultOperation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(display, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resultOperation, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(number2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(number1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(number3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(multiplicationOperation, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(number4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(number5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(number6, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(divisionOperation, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(number7, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(number8, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(number9, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subtractionOperation, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(number0, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(commaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sumOperation, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OnClear(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OnClear
        this.display.setText("");
    }//GEN-LAST:event_OnClear

    private void onDelete(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onDelete
        String userInput = this.display.getText();

        if (!userInput.isBlank()) {
            this.display.setText(userInput.substring(0, userInput.length() - 1));
        }
    }//GEN-LAST:event_onDelete

    private void onClickComma(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onClickComma
        String userInput = this.display.getText();

        if (!userInput.isEmpty()) {
            String[] parts = userInput.split("[-+*/]");
            String lastNumber = parts[parts.length - 1];

            if (!lastNumber.contains(",")) {
                char lastChar = userInput.charAt(userInput.length() - 1);
                if (operations.contains(String.valueOf(lastChar))) {
                    this.display.setText(userInput + "0,");
                } else {
                    this.display.setText(userInput + ",");
                }
            }
        } else {
            this.display.setText("0,");
        }


    }//GEN-LAST:event_onClickComma

    private void none(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_none
        // TODO add your handling code here:
    }// GEN-LAST:event_none

    private void onClickNumber(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_onClickNumber
        JButton button = (JButton) evt.getSource();
        String number = button.getText();

        this.display.setText(this.display.getText() + number);

    }// GEN-LAST:event_onClickNumber

    private void onClickOperation(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_onClickOperation
        JButton button = (JButton) evt.getSource();
        String operation = button.getText();

        String userInput = this.display.getText();

        if (!userInput.isBlank()) {
            char lastChar = userInput.charAt(userInput.length() - 1);
            if (Character.isDigit(lastChar)) {
                this.display.setText(userInput + operation);
            } else {
                String updatedDisplay = userInput.substring(0, userInput.length() - 1);
                this.display.setText(updatedDisplay + operation);
            }
        } else {
            if (operation.equals("-")) {
                this.display.setText("-");
            }
        }

    }// GEN-LAST:event_onClickOperation

    private void setErrorStyle() {
        this.display.setBorder(this.errorBorder);
        this.display.setBackground(this.rosaForte);
    }

    private void setDefaultStyle() {
        this.display.setBorder(this.defaultBorder);
        this.display.setBackground(this.rosaClaro);
    }

    private void updateStyle() {
        String userInput = this.display.getText();

        if (!userInput.isBlank()) {
            char lastChar = userInput.charAt(userInput.length() - 1);

            if (Character.isDigit(lastChar)) {
                setDefaultStyle();
            } else {
                setErrorStyle();
            }
        } else {
            setErrorStyle();
        }

    }

    private Double calculate(String operation, Double number1, Double number2) {
        switch (operation) {
            case "+":
                return number1 + number2;
            case "-":
                return number1 - number2;
            case "*":
                return number1 * number2;
            case "/":
                if (number2 == 0) {
                    setErrorStyle();
                    return 0.0;
                }

                return number1 / number2;
            default:
                return 0.0;
        }

    }

    private int prioridade(String op) {
        if (op.equals("*") || op.equals("/")) {
            return 1;
        }

        return 0;
    }

    private List<String> getPostFixExpression() {
        String text = this.display.getText().replace(",", ".");
        String[] input = text.split("(?<=[-+*/])|(?=[-+*/])");

        List<String> inputList = new ArrayList<>(Arrays.asList(input));
        List<String> outputList = new ArrayList<>();
        List<String> operationsList = new ArrayList<>();

        if (!inputList.isEmpty()) {
            if (Character.isDigit(inputList.getLast().charAt(0))) {
                if (inputList.getFirst().equals("-")) {
                    inputList.addFirst("0");
                }

                for (String character : inputList) {
                    if (this.operations.contains(character)) {
                        while (!operationsList.isEmpty() && prioridade(
                                operationsList.getLast()) >= prioridade(character)) {
                            outputList.add(operationsList.removeLast());
                        }

                        operationsList.add(character);
                    } else {
                        outputList.add(character);
                    }
                }

                while (!operationsList.isEmpty()) {
                    outputList.add(operationsList.removeLast());
                }

                System.out.println("Lista DEPOIS: " + outputList);
                return outputList;

            }

        }

        return new ArrayList<>();
    }

    private void onResult(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_onResult
        this.updateStyle();

        List<String> expression = this.getPostFixExpression();

        for (String character : expression) {
            if (operations.contains(character)) {
                Double num2 = Double.parseDouble(stack.pop());
                Double num1 = Double.parseDouble(stack.pop());
                Double result = calculate(character, num1, num2);
                stack.push(String.valueOf(decimalFormat.format(result)));
            } else {
                stack.push(character);
            }
        }

        if (!expression.isEmpty()) {
            this.display.setText(stack.pop());
        }

        this.stack.clear();

    }// GEN-LAST:event_onResult

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel.
                 * For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                    .getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(
                    java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(
                    java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(
                    java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(
                    java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearButton;
    private javax.swing.JButton commaButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField display;
    private javax.swing.JButton divisionOperation;
    private javax.swing.ButtonGroup functionsGroup;
    private javax.swing.JButton multiplicationOperation;
    private javax.swing.JButton number0;
    private javax.swing.JButton number1;
    private javax.swing.JButton number2;
    private javax.swing.JButton number3;
    private javax.swing.JButton number4;
    private javax.swing.JButton number5;
    private javax.swing.JButton number6;
    private javax.swing.JButton number7;
    private javax.swing.JButton number8;
    private javax.swing.JButton number9;
    private javax.swing.ButtonGroup numbersGroup;
    private javax.swing.ButtonGroup operationsGroup;
    private javax.swing.JButton resultOperation;
    private javax.swing.JButton subtractionOperation;
    private javax.swing.JButton sumOperation;
    // End of variables declaration//GEN-END:variables
}
